### ISSUE TITLE
K80 GPUs are ignored

### ISSUE THREAD

**Issue by fshriver** [tlkh/ai-lab#30]
**Describe the bug**
For `19.09`, tensorflow appears to ignore K80 GPUs due to them having a compute capability of 3.7. Specifically, the message returned by tensorflow is:

`Ignoring visible gpu device (device: 0, name: Tesla K80, compute capability: 3.7) with Cuda compute capability 3.7. The minimum required Cuda capability is 6.0.`

**To Reproduce**
1. Pull image down.
2. Start container.
3. From shell run `python3`
4. Once inside python session, run `import tensorflow as tf` and then `tf.test.gpu_device_name()`

**Expected behavior**
Expect it to identify the K80s and attach to them, especially as the tensorflow GPU page lists hardware requirements as being only compute capability 3.5 or above (https://www.tensorflow.org/install/gpu).

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: [Linux]
 - Browser [N/A]

**Container Version**
`19.09`

**Additional context**
I'm confused on whether this is a tensorflow issue or a specific container issue, since tensorflow does not seem to indicate they've removed support for K80s.

**Comment by tlkh** [comment]
Hello, K80 is not supported for this container.

Supported compute capability are:

- 6.0 (P100)
- 6.1 (GTX 10XX)
- 7.0 (V100)
- 7.5 (RTX 20XX)

**Comment by fshriver** [comment]
Ah, alright. Might I suggest adding a 'Supported compute capabilities' tab under the FAQ then? Just a thought, but otherwise I'm closing this issue.
